version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - redis

  worker:
    build: .
    command: rq worker
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
